### ISSUE TITLE
Where's the source?

### ISSUE THREAD

**Issue by ickc** [freehkfonts/freehkkai#7]
Where's the source? I don't seem to find that...

**Comment by ickc** [comment]
Another related issue is to link back to the source. From the description, it seems that this a a fork of an open source font from Taiwan.

**Comment by danvim** [comment]
@ickc I believe the project is well credited and is not too similar to Taiwanese font and therefore, it itself can become its own "master" and need not provide a link to the origin project.

**Comment by ickc** [comment]
@danvim

Which project is well credited? If you mean the Taiwan font project is well credited, I still do not know which font they are talking about. That's why I need a link.

And linking back to the original is not mandatory. But I consider not doing so is rude and hurting developments in general. The Chinese community usually don't care this kind of stuff. Wonder why we have 4,000 + years of history and practically all modern knowledge which we depends on daily is not in Chinese (I'm not talking about translated materials)? Because we are weak at the propagation of knowledge.

**Comment by danvim** [comment]
quoting: *"「自由香港楷書」4700字版 開放授權條款：*

*字體標準來源： 1.「自由香港楷書(Free HK Kai)」(下稱本字型) 是根據香港特別行區教育局課程發展處中國語文教育組於2012年所編制出版的《常用字字形表(2007年重排本)》為楷書字型基礎作出修改。 2.本字型為「自由香港楷書」4700字版，根據《常用字字形表(2007年重排本)》共有4,762個小學生常用字。 **3.本字型修改來源於台灣全字庫正楷體(中華民國行政院國家發展委員會，CNS11643中文標準交換碼全字庫網站，http://www.cns11643.gov.tw )**。"*

Also on the 全字庫 website: "*全字庫授權聲明*

*授權方式及範圍*

*本網站以無償及非專屬授權方式授權使用者得不限時間及地域，重製、編輯、公開傳輸或為其他利用方式，開發各種產品或服務（以下簡稱加值產品），但授權範圍不包含商標權及專利權。*

*使用者公開發行、公開展示或其他利用本網站相關字型、資料、元件或程式所產生之加值產品，應以適當方式註明字型、資料、元件或程式之來源出處(中華民國國家發展委員會，CNS11643中文標準交換碼全字庫網站，http://www.cns11643.gov.tw。)"*

I hate to say this, but may I also suggest not to rant about ideas that are irrelevant to any project. It is usually a good choice.

**Comment by ickc** [comment]
This should be in the readme.

This is wrong but common practice — no one is reading the license. If you said you do, you will be a liar. e.g. recall last time you install any software and did you read through the license/EULA before you click agree?

Second, you fail to link back again. Now I don't know where that "「自由香港楷書」4700字版 開放授權條款" is from. You might say one can just google it. But why don't you just put the link there but let the others to rely on search engine that can link to a different page you were citing from?

And after all these messages going back and forth, I still don't know where the source code of this project is, which is the main title of this issue.

And then you still haven't clarify "Which project is well credited?".

And when you say

> not too similar to Taiwanese font

It is really up to interpretation. In my view, it only adds minor modifications. It is a "mutation of the same thing".

But to @freehkfonts' credit, I can't find the source code from <http://www.cns11643.gov.tw> (at least within a few clicks). So they set a really bad example of open source development already, and how can one expect a fork of that project will be better?

Something @freehkfonts can help when linking back is, rather than linking to the root of the website <http://www.cns11643.gov.tw>, they should link it to the source code where they download it. That would be a great help (even if I exhaust all the buttons there and finally found their source code, why everyone has to repeat the pain of thousands click?).

All in all, what I am asking for is clarity, better communication, and openness. If the "free" there isn't just free as in beer but free as in free speech, this should be done. Otherwise, the project really doesn't have much value, since it is not "owned by Hong Kong people". i.e. not any Hong Kong people can edit the source and contribute.

**Comment by danvim** [comment]
@ickc I really don't want to argue.

> no one is reading the license

> Now I don't know where that "「自由香港楷書」4700字版 開放授權條款" is from.

It **is** a README from the download branch. (not sure why though)

---

> I still don't know where the source code of this project is, which is the main title of this issue.

The problem is not on this side, because the origin authoring organization asks to be credited at `http://www.cns11643.gov.tw/`. You can feel free to go on their site and maybe contact the Taiwanese government (since 全字庫 is a government project) for poor website UX design.

After researching, I don't believe 全字庫楷 is a ready bundled `.ttf` font. Rather it is generated by its software.

quoting [全字庫網頁使用手冊](http://tx.liberal.ntu.edu.tw/tools/%E4%B8%AD%E6%96%87%E6%A8%99%E6%BA%96%E4%BA%A4%E6%8F%9B%E7%A2%BC/%E5%85%A8%E5%AD%97%E5%BA%AB4.0/cnsmanual92_2.doc): "*◆全字庫應用架構：*
_1.中文字庫(中文版&英文版)。
2.**下載機制─自行下載所缺的自造字，匯入系統造字區。**
3.即時顯示─透過網際網路，即時瀏覽與編輯全字庫的字集。
4.共通平台─輸入、顯示、轉換及儲存模組，以用於異碼資訊系統之互通。
5.多語文互換及檢索模組。
6.文字相關線上遊戲。*_"

and referring to: http://www.cns11643.gov.tw/AIDB/usages.do

I retract my first reply, because there is simply no "open source project webpage" link to be provided other than the root URL because the 全字庫楷 font has no actual project website. Or you can also say their root URL is their actual project website. **Their main "open" in open source refers to each individual glyph collected from physical papers and digitally crafted, as they are not directly aiming for providing ready packaged font files**.

However, this is where they link you to download the complete font: http://www.cns11643.gov.tw/AIDB/cns_authorization_apply.do which links to a page on the Taiwanese government database website. **Then, citing that external link as source would seem inappropriate**.
